### ISSUE TITLE
Неправильная дата транзакции в событиях с TransactionStatus="Нет транзакции"

### ISSUE THREAD

**Issue by akpaevj** [YPermitin/YY.EventLogExportAssistant#29]
**Описание ошибки**
После экспорта в БД (ClickHouse), в записях таблицы RowsData с TransactionStatus = "Нет транзакции" записано значение даты (TransactionDate), отличающееся от исходных данных события. В исходных данных значение 0, а в БД - дата с годом 2042.

**Как воспроизвести**
1. Смотреть в событиях проблемного типа

![20201106_210053](https://user-images.githubusercontent.com/40080662/98399374-54be0800-2073-11eb-9e22-d789d96b260a.jpg)
![20201106_210132](https://user-images.githubusercontent.com/40080662/98399394-5be51600-2073-11eb-9eae-686b3277ff0a.jpg)

**Ожидаемое поведение**
0001.01.01 00:00:00 (только предложение:))

**Информация для расследования:**
 - 8.3.16
 - ClickHouse
 - Windows 10

**Comment by YPermitin** [comment]
Это ошибка на стороне ClickHouse:
https://github.com/ClickHouse/clickhouse-go/issues/177
https://github.com/ClickHouse/ClickHouse/issues/3470

При вставке пустых дат происходит некорректная конвертация.
Пока оставлю текущую реализацию, возможно поведение изменится в будущих версиях CH.

**Comment by akpaevj** [comment]
Да, у себя тоже вижу уже:(
