### ISSUE TITLE
Ошибка загрузки журнала регистрации

### ISSUE THREAD

**Issue by okwell5** [YPermitin/YY.EventLogExportAssistant#48]
**Описание ошибки**
Простое и понятное описание ошибки.
После инициализации во время загрузки выскочила ошибка "Экспорт остановлен из-за ошибки".

**Как воспроизвести**
Последовательность шагов для воспроизведения ошибки:
1. Скачать графическое приложение из публикации: https://infostart.ru/public/1240376/
2. Заполнить настройки. В настройках указать имя новой базы. Нажать на 'Проверить подключение'. 
3. Нажать  'Запустить выгрузку'
4. Смотреть ошибку, приложил. В папке с журналом регистрации логи приложения отсутствуют.
![Err of JR 2021-04-13 13-13-33](https://user-images.githubusercontent.com/20970771/114544553-798e5b00-9c63-11eb-9080-74f76285e924.png)

**Ожидаемое поведение**
Экспорт должен завершиться успешно, как в публикации.

**Скриншоты**
Приложил.

**Информация для расследования:**
 - Версия платформы 1С: без 1С. Журнал регистрации велся на платформе 8.3.17.1851.
 - Назначение экспорта (какая СУБД, версия и др.): Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
 - Операционная система: Windows Server 2016 Standard
 - Файл журнала регистрации по возможности: По запросу скину на почту (мой email: wellok5@gmail.com). 

**Дополнительная информация**
Просьба сделать пропуск ошибки, как в 1С Попытка Исключение КонецПопытки. Пропуск ошибки нужен, чтобы загрузить остальные все данные. Строка журнала, на которой возникла ошибка, даже не нужна.

**Comment by okwell5** [comment]
Нашел логи, приложил: https://disk.yandex.ru/d/AN8aY4UXTTi1Rg

**Comment by YPermitin** [comment]
@okwell5 Были применены некоторые изменения по обработке формата LGP.
Информацию отправил, можно проверять.

**Comment by YPermitin** [comment]
Закрываю.

Если будут другие вопросы, то разберем отдельными Issue.
